FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
ENV ASPNETCORE_URLS=http://+:5001
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["./Mvc.csproj", "./"]
RUN dotnet restore "Mvc.csproj"
COPY . .
RUN dotnet build "./Mvc.csproj" -c Release -o /app/build
FROM build AS publish
RUN dotnet publish "./Mvc.csproj" -c Release -o /app/publish
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "/app/Mvc.dll"]
