
version: '3.7'
services:
 projet:
  build:
   context : ./Mvc/
   dockerfile : Dockerfile
  container_name : project_mvc
  volumes:
      - ./:/var/www
  expose:
   - "5000"
  depends_on:
   - nginx_proxy
  restart : always

 nginx_proxy:
  build:
    context : ./nginx/
    dockerfile : Dockerfile
  container_name: nginx_mvc
  volumes:
   - ./:/var/www
  ports:
   - "4001:80" 
  restart : always